####################################################################################################
# < Doflake > Themes
####################################################################################################
# ä¸»é¢˜ç®€ä»‹
# 
#   ä¸»é¢˜å : Doflake 
#     åå­—æ€è·¯æ¥æº : [å…ƒç¥–]Dove & [å…ƒç¥–]Beelake åå­—åˆæˆ (Dof & Lake)
#
#   ç›®å‰å­˜åœ¨ 2 å å¼€å‘äººå‘˜  ( --ğŸ˜æ¬¢è¿åŠ å…¥ğŸ˜-- )
#     1. [å…ƒç¥–] Dove : å®ç°ä¸»é¢˜ (åŠŸèƒ½ , æ ·å¼ , å¸ƒå±€)
#     2. [å…ƒç¥–] Beelake : æ–‡ç«  , æŸ¥è¯¢èµ„æ–™ , æ‰¾æ–°åŠŸèƒ½
#   
#   ä¸»é¢˜åšå®¢ : https://doflake.github.io/
#     æ³¨é‡Š : ä¸»é¢˜åšå®¢ ä¸æ­¢æœ‰ ä¸»é¢˜ç›¸å…³å†…å®¹ è¿˜æœ‰ Doflake çš„å…¶ä»–æ–‡ç«  
#            ä¸»é¢˜ç›¸å…³å†…å®¹ å‡åœ¨ ä¸»é¢˜æ–‡æ¡£ ä¸­
#   ä¸»é¢˜æ–‡æ¡£ : https://doflake.github.io/doflake-document/
#     æ³¨é‡Š : åŒ…å« "ä¸»é¢˜ç®€ä»‹" "ä¸»é¢˜ä¸‹è½½" "ä¸»é¢˜é£Ÿç”¨" "ä¸»é¢˜å‘å±•å²" ç­‰å†…å®¹ 
#
# å…¶ä»–
#
#   å¤šå¤šæ”¯æŒï¼Œååˆ†æ„Ÿè°¢
#   å¦‚æœ æœ‰å¥½çš„æè®® Doflake éƒ½ä¼šå¬çš„
#
# -------------------------------------------------------------------------------------------------- 

####################################################################################################
# Basic Settings åŸºç¡€è®¾ç½®
####################################################################################################
basic:
  
## Info åŸºæœ¬ä¿¡æ¯
# **************************|*********************************
# info:                     |
#  title:                   |   ç½‘é¡µæ ‡é¢˜
#  favicon:                 |   ç½‘é¡µå›¾æ ‡ 
#  author:                  |   ç¬¬ä¸€ç¯‡æ–‡ç« ä¸Šæ–¹çš„æ–‡å­—
# **************************|*********************************
  info:
   title: Doflake
   favicon: https://cdn.jsdelivr.net/gh/doflake/Picture/Favicon/1.jpg
   author: Doflake

## Menu å¯¼èˆªæ 
# **************************|*********************************
# Example:                  |
#   [AA]:                   |   å¯¼èˆªæ ä¸­ç»„ä»¶åç§°
#     name:                 |   å†…å®¹
#     link:                 |   è·³è½¬é“¾æ¥  
# **************************|*********************************
  menu:
   Home: 
     name: ä¸»é¡µ
     link: /
   Document:
     name: ä¸»é¢˜æ–‡æ¡£
     link: /doflake-document/
   Archives:
     name: å½’æ¡£
     link: /archives/
   Github: 
     name: Github
     link: https://github.com/doflake/


## Background èƒŒæ™¯å›¾
# **************************|*********************************
# background:               |
#   link:                   |   å›¾ç‰‡é“¾æ¥
#   layout:                 |   æ ·å¼
#     repeat:               |   æ˜¯å¦é‡å¤
#     attachment:           |   å›ºå®š æˆ– éšæ»šåŠ¨ç§»åŠ¨
#     size:                 |   å›¾ç‰‡å¤§å°
# **************************|*********************************
  background:
   link: https://cdn.jsdelivr.net/gh/doflake/Picture/Background/3.jpg
   layout:
     repeat: no-repeat
     attachment: fixed
     size: auto auto


## Mathjax æ¸²æŸ“å…¬å¼
# **************************|*********************************
# ä½¿ç”¨:
#   ç§»é™¤ marked æ¸²æŸ“å™¨ npm uninstall hexo-renderer-marked --save
#   å®‰è£… kramed æ¸²æŸ“å™¨ npm install hexo-renderer-kramed --save
# Attention : å¼€å¯åé»˜è®¤ä¸ºæ‰€æœ‰å…¬å¼å…¨éƒ¨æ¸²æŸ“ (åŒ…æ‹¬ æ ‡é¢˜ ç­‰)
# **************************|*********************************
  mathjax:
   enable: true

# -------------------------------------------------------------------------------------------------- < End Basic Setting >

####################################################################################################
# Layout å¸ƒå±€
####################################################################################################
layout:

## Index_post ä¸»é¡µæ–‡ç« å—
# **************************|*********************************
# index_post:               |   æ–‡ç« æ–¹æ¡†
#   container:              |   æ–‡ç« å—
#     max_width:            |   æœ€å¤§å®½åº¦ 
#     left:                 |   å·¦è¾¹è·
#     top:                  |   ä¸Šè¾¹è·
#     right:                |   å³è¾¹è·
#     bottom:               |   ä¸‹è¾¹è·
#     color:                |   åº•è‰²
#   border:                 |   è¾¹æ¡†æ ·å¼
#     radius:               |   æ–‡ç« åœ†è§’
#   margin:                 |   è¾¹è·
#     first_to_nav:         |   ç¬¬ä¸€ç¯‡æ–‡ç«  åˆ° å¯¼èˆªæ  çš„è·ç¦»
#   posts:                  |   æ–‡ç« å†…å®¹
#     title_color:          |   æ ‡é¢˜é¢œè‰²
#     content_link_color:   |   æ–‡ç« å†…å®¹ä¸­é“¾æ¥é¢œè‰² 
# **************************|*********************************
  index_post:
    container:
      max_width: 960px
      left: 100px
      top: auto
      right: auto
      bottom: auto
      color: 
        default: 255,255,255,0.8
        hover: 255,255,255,0.9
    border:
      radius: 10px
    margin:
      first_to_nav: 5px
    posts:
      title_color: "#5C6FDA"
      content_link_color: "#1198B6"
    
# -------------------------------------------------------------------------------------------------- < End Layout >

####################################################################################################
# Meta ç»„ä»¶
####################################################################################################
meta:

## Totop å‰å¾€é¡¶ç«¯
# **************************|*********************************  
# totop:                    |   å‰å¾€é¡¶ç«¯
#   enable:                 |   æ˜¯å¦å¯ç”¨
# **************************|*********************************  
  totop: 
    enable: true

## Clock æ—¶é’Ÿ
# **************************|*********************************  
# clock:                    |   éœ“è™¹ç¯ æ—¶é’Ÿ
#   enable:                 |   æ˜¯å¦å¯ç”¨
#   layout:                 |   æ ·å¼
#     size:                 |   æ—¶é’Ÿ å¤§å°
#     fill:                 |   æ—¶é’Ÿ å­—ä½“é¢œè‰²
#     stroke_width:         |   éœ“è™¹ç¯å¸¦ å®½åº¦
#     time:                 |   éœ“è™¹ç¯å¸¦ èµ°å®Œä¸€æ¬¡æ—¶é•¿
# **************************|*********************************  
  clock:
    enable: true
    layout:
      size: 45px
      fill: "#000000"
      stroke_width: 3px
      time: 8

# -------------------------------------------------------------------------------------------------- < End Meta >
