####################################################################################################
# < Doflake > Themes
####################################################################################################
# ä¸»é¢˜ç®€ä»‹
# 
#   ä¸»é¢˜å : Doflake 
#     åå­—æ€è·¯æ¥æº : [å…ƒç¥–]Dove & [å…ƒç¥–]Beelake åå­—åˆæˆ (Dof & Lake)
#
#   ç›®å‰å­˜åœ¨ 2 å å¼€å‘äººå‘˜  ( --ğŸ˜æ¬¢è¿åŠ å…¥ğŸ˜-- )
#     1. [å…ƒç¥–] Dove : å®ç°ä¸»é¢˜ (åŠŸèƒ½ , æ ·å¼ , å¸ƒå±€)
#     2. [å…ƒç¥–] Beelake : æ–‡ç«  , æŸ¥è¯¢èµ„æ–™ , æ‰¾æ–°åŠŸèƒ½
#   
#   ä¸»é¢˜åšå®¢ : https://doflake.github.io/
#     æ³¨é‡Š : ä¸»é¢˜åšå®¢ ä¸æ­¢æœ‰ ä¸»é¢˜ç›¸å…³å†…å®¹ è¿˜æœ‰ Doflake çš„å…¶ä»–æ–‡ç«  
#            ä¸»é¢˜ç›¸å…³å†…å®¹ å‡åœ¨ ä¸»é¢˜æ–‡æ¡£ ä¸­
#   ä¸»é¢˜æ–‡æ¡£ : https://doflake.github.io/Do/Doflake-Theme-Document/
#     æ³¨é‡Š : åŒ…å« "ä¸»é¢˜ç®€ä»‹" "ä¸»é¢˜ä¸‹è½½" "ä¸»é¢˜é£Ÿç”¨" "ä¸»é¢˜å‘å±•å²" ç­‰å†…å®¹ 
#
# å…¶ä»–
#
#   å¤šå¤šæ”¯æŒï¼Œååˆ†æ„Ÿè°¢
#   å¦‚æœ æœ‰å¥½çš„æè®® Doflake éƒ½ä¼šå¬çš„
#
# -------------------------------------------------------------------------------------------------- 

####################################################################################################
# Basic Settings åŸºç¡€è®¾ç½®
####################################################################################################
basic:
  
## Info åŸºæœ¬ä¿¡æ¯
# **************************|*********************************
# info:                     |
#  title:                   |   ç½‘é¡µæ ‡é¢˜
#  favicon:                 |   ç½‘é¡µå›¾æ ‡ 
#  author:                  |   ç¬¬ä¸€ç¯‡æ–‡ç« ä¸Šæ–¹çš„æ–‡å­—
# **************************|*********************************
  info:
   title: Doflake
   favicon: https://cdn.jsdelivr.net/gh/doflake/Picture/Favicon/1.jpg
   author: Doflake

## Menu å¯¼èˆªæ 
# **************************|*********************************
# Example:                  |
#   [AA]:                   |   å¯¼èˆªæ ä¸­ç»„ä»¶åç§°
#     name:                 |   å†…å®¹
#     link:                 |   è·³è½¬é“¾æ¥  
# **************************|*********************************
  menu:
   Home: 
     name: ä¸»é¡µ
     link: /
   Archives:
     name: å½’æ¡£
     link: /archives
   Github: 
     name: Github
     link: https://github.com/doflake/


## Background èƒŒæ™¯å›¾
# **************************|*********************************
# background:               |
#   enable:                 |   æ˜¯å¦ä½¿ç”¨èƒŒæ™¯å›¾
#   link:                   |   å›¾ç‰‡é“¾æ¥
# **************************|*********************************
  background:
   link: https://cdn.jsdelivr.net/gh/doflake/Picture/Background/2.jpg

## Mathjax æ¸²æŸ“å…¬å¼
# **************************|*********************************
# ä½¿ç”¨:
#   ç§»é™¤ marked æ¸²æŸ“å™¨ npm uninstall hexo-renderer-marked --save
#   å®‰è£… kramed æ¸²æŸ“å™¨ npm install hexo-renderer-kramed --save
# **************************|*********************************
  mathjax:
   enable: true

# -------------------------------------------------------------------------------------------------- < End Basic Setting >

####################################################################################################
# Layout å¸ƒå±€
####################################################################################################
layout:
## ä¸»é¡µæ–‡ç« å—
# **************************|*********************************
# index_post:               |   æ–‡ç« æ–¹æ¡†
#   max_width:              |   æœ€å¤§å®½åº¦ 
#   left:                   |   å·¦è¾¹è·
#   top:                    |   ä¸Šè¾¹è·
#   right:                  |   å³è¾¹è·
#   bottom:                 |   ä¸‹è¾¹è·
#   radius:                 |   æ–‡ç« åœ†è§’
# **************************|*********************************
  index_post:
    max_width: 960px
    left: 100px
    top: auto
    right: auto
    bottom: auto
    radius: 10px

## èƒŒæ™¯å›¾ç‰‡
# **************************|*********************************
# background:               |   èƒŒæ™¯å›¾ç‰‡
#   repeat:                 |   æ˜¯å¦é‡å¤
#   attachment:             |   å›ºå®š æˆ– éšæ»šåŠ¨ç§»åŠ¨
#   size:                   |   å›¾ç‰‡å¤§å°
# **************************|*********************************
  background:
    repeat: no-repeat
    attachment: fixed
    size: auto auto
    